### ISSUE TITLE
video 업로드 시 

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#102]
## 서버 환경
- localhost (dev)
- commit 57e0295d

### 발생 상황
`api/observe/video`로 비디오 업로드 시 발생. -> 응답은 제대로옴
<img width="605" alt="image" src="https://github.com/BatShu/batshu-backend/assets/42014299/50344521-ff71-4854-8604-3b7917403d40">

아무래도 recursive하게 폴더를 생성하는게 원인인 것 같음.

### 서버 터미널
```
썸네일 추출 완료
Error: Unknown column 'thumbnail_url' in 'field list'
    at PromisePoolConnection.query (/Users/bluejoy/development/projects/batshu-backend/node_modules/mysql2/promise.js:94:22)
    at /Users/bluejoy/development/projects/batshu-backend/src/Repository/ObserveRepository.ts:72:58
    at step (/Users/bluejoy/development/projects/batshu-backend/src/Repository/ObserveRepository.ts:33:23)
    at Object.next (/Users/bluejoy/development/projects/batshu-backend/src/Repository/ObserveRepository.ts:14:53)
    at /Users/bluejoy/development/projects/batshu-backend/src/Repository/ObserveRepository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bluejoy/development/projects/batshu-backend/src/Repository/ObserveRepository.ts:4:12)
    at insertThumbnailUrlResult (/Users/bluejoy/development/projects/batshu-backend/src/Repository/ObserveRepository.ts:70:165)
    at /Users/bluejoy/development/projects/batshu-backend/src/service/ObserveService.ts:75:51
    at step (/Users/bluejoy/development/projects/batshu-backend/src/service/ObserveService.ts:33:23) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "UPDATE video SET video_url = 'https://batshu-observe-input.s3.amazonaws.com/á\x84\x92á\x85ªá\x84\x86á\x85§á\x86« á\x84\x80á\x85µá\x84\x85á\x85©á\x86¨ 2023-07-19 á\x84\x8Bá\x85©á\x84\x92á\x85® 4.14.34.mov', thumbnail_url = 'https://batshu-observe-input.s3.amazonaws.com/thumbnail_1698393438500Toá\x84\x92á\x85ªá\x84\x86á\x85§á\x86« á\x84\x80á\x85µá\x84\x85á\x85©á\x86¨ 2023-07-19 á\x84\x8Bá\x85©á\x84\x92á\x85® 4.14.34.mov.png' WHERE video_url = 'á\x84\x92á\x85ªá\x84\x86á\x85§á\x86« á\x84\x80á\x85µá\x84\x85á\x85©á\x86¨ 2023-07-19 á\x84\x8Bá\x85©á\x84\x92á\x85® 4.14.34.mov';",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'thumbnail_url' in 'field list'"
}
```

**Comment by bik1111** [comment]
@bluejoyq 

<img width="315" alt="스크린샷 2023-10-28 오전 10 52 07" src="https://github.com/BatShu/batshu-backend/assets/76617139/f27a09de-e669-4782-a227-9940679e6133">

기존에 thumnail 이라고 되있었는데, 코드 상에서는 thum"b"nail이라고 되어있어서 인식이 안된 것 같습니다.

노션 수정 ✅

**Comment by bluejoyq** [comment]
@bik1111 추가로 mysql volume 삭제 후 재생성을 통해 테이블 컬럼을 수정해줘야 했습니다.
