### ISSUE TITLE
bug: 간헐적으로 새로 고침 시 무한 로딩

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#139]
## 설명
![image](https://github.com/BatShu/batshu-backend/assets/42014299/f830ce85-5e2a-4864-b6ef-0c235839fbe2)

매우 자주 새로고침 시 유저 정보 불러오는 부분이 무한 pending됨.

### 백엔드 메세지
추정
```
Error: FirebaseAuthError: There is no user record corresponding to the provided identifier.
    at /Users/bluejoy/development/projects/batshu-backend/node_modules/firebase-admin/lib/auth/auth-api-request.js:551:15
    at /Users/bluejoy/development/projects/batshu-backend/node_modules/firebase-admin/lib/auth/auth-api-request.js:1615:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorInfo: {
    code: 'auth/user-not-found',
    message: 'There is no user record corresponding to the provided identifier.'
  },
  codePrefix: 'auth'
}
```

**Comment by HYEOK9** [comment]
이건 큰데

**Comment by bluejoyq** [comment]
```tsx
export const readUser = async (uid: string): Promise<UserRow[]> => {
  const connection = await pool.getConnection();
  const [user]: [UserRow[], FieldPacket[]] = await connection.execute('SELECT * FROM user WHERE uid = ?', [uid]);
  connection.release();
  return user;
};

```

여기서 코드가 멈춤
